version: '3.8'

services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: bonsay_api
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3020:3020
    networks:
      - bonsay

volumes:
  data:
    name: bonsay_data

networks:
  bonsay:
    external: true

secrets:
  postgres_password:
    file: ./docker_postgres_password
